---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include install tasks.
  include: "install-{{ ansible_os_family }}.yml"

- name: Template a file to telegraf.conf
  template:
    src: telegraf.conf.j2
    dest: "{{ telegraf_conf_file }}"
    mode: "0644"

- name: Start service telegraf
  service:
    name: telegraf
    state: "{{ telegraf_state }}"
    enabled: "{{ telegraf_enabled }}"
